name: pelatihan_kemendagri
description: "A new Flutter project for Pelatihan Kemendagri."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.0.0
  provider: ^6.1.2
  file_selector: ^1.0.3
  http: ^0.13.5
  image_picker: ^1.0.4
  url_launcher: ^6.2.5
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Versi terbaru saat ini (kamu bisa sesuaikan)

flutter:
  uses-material-design: true

  assets:
    - assets/images/
